# Generated by Django 5.0.3 on 2024-03-06 02:44

import django.db.models.deletion
import django_resized.forms
import optics.opticsapp.models.Squadron
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadron_name', models.CharField(max_length=50, unique=True, verbose_name='Squadron Name')),
                ('squadron_url', models.URLField(null=True, verbose_name='Squadron Website')),
            ],
            options={
                'db_table': 'user_squadron',
            },
        ),
        migrations.CreateModel(
            name='ThreatReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('nato_code', models.CharField(max_length=60)),
                ('threat_class', models.CharField(choices=[('AAA', 'AAA'), ('MANPAD', 'MANPAD'), ('SHORAD', 'SHORAD'), ('MEDRAD', 'MEDRAD'), ('LONRAD', 'LONRAD'), ('TGTRDR', 'TGTRDR'), ('EWR-ACQR', 'EWR-ACQR')], max_length=10, null=True)),
                ('threat_type', models.CharField(choices=[('OPTICAL', 'OPTICAL'), ('RADAR', 'RADAR'), ('LASER', 'LASER'), ('IR', 'IR')], max_length=10, null=True)),
                ('gun_ammo', models.IntegerField(default=0, help_text='Number of gun rounds.')),
                ('missile_ammo', models.IntegerField(default=0, help_text='Number of missiles.')),
                ('range_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum engagement range (nmi).', max_digits=8)),
                ('range_max', models.DecimalField(decimal_places=2, default=0, help_text='Maximum enagengagementement range (nmi).', max_digits=8)),
                ('alt_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum engagement altitude (ft).', max_digits=8)),
                ('alt_max', models.DecimalField(decimal_places=2, default=0, help_text='Maximum engagement altitude (ft).', max_digits=8)),
                ('acquire_time', models.DecimalField(decimal_places=2, default=0, help_text='Time to acquire (secs).', max_digits=8)),
                ('rwr_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier')),
                ('rwr_image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier')),
                ('rwr_image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier')),
                ('harm_code', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Threat Reference',
                'verbose_name_plural': 'Threat References',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Enter the service/app the webhook is for', max_length=30, verbose_name='Service Name')),
                ('url', models.CharField(help_text='Enter the web hook URL.', max_length=255, verbose_name='Web Hook URL')),
            ],
            options={
                'ordering': ['-service_name'],
            },
        ),
        migrations.CreateModel(
            name='Airframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Airframe Name', max_length=200)),
                ('stations', models.IntegerField(default=2)),
                ('multicrew', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirframeDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(help_text='Call sign for this type of airframe.', max_length=20)),
                ('default_radio_freq', models.CharField(help_text='Default radio frequency.', max_length=15)),
                ('laser_code', models.CharField(help_text='Starting laser code.', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('airframe_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.airframe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Airframe Defaults',
                'verbose_name_plural': 'Airframe Defaults',
                'ordering': ['-airframe_type', '-callsign'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The Campaign Name.', max_length=200, verbose_name='Campaign Name')),
                ('description', models.TextField(default='Campaign description to be added here.', help_text='A brief description used for display purposes on selection screens.', verbose_name='Campaign Description')),
                ('start_date', models.DateField(blank=True, help_text='Proposed Start Date of Campaign.', null=True, verbose_name='Expected Start Date')),
                ('campaignImage', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Campaign Image File.', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image Thumbnail.')),
                ('situation', models.TextField(blank=True, help_text='A detailed overview of the background and situation for the campaign.', null=True)),
                ('aoImage', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='An image of the Area of Operations.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/ao_images', verbose_name='area of Operations Image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(help_text='Enter Flight Callsign', max_length=200)),
                ('flight_coordination', models.TextField(blank=True, help_text='Use this field to enter in any notes that the flight lead might need to use to coordinate other members of the flight,', null=True, verbose_name='Notes for flight co-ordination')),
                ('radio_frequency', models.CharField(blank=True, help_text='Enter Flight Frequency', max_length=20, null=True)),
                ('tacan', models.CharField(blank=True, help_text='Enter Flight TACAN (if applicable)', max_length=5, null=True)),
                ('timehack_start', models.CharField(blank=True, help_text='Enter time for flight takeoff.', max_length=10, null=True, verbose_name='Takeoff Time')),
                ('timehack_rdv1', models.CharField(blank=True, help_text='Enter time for flight rendevous point 1.', max_length=10, null=True, verbose_name='Time RDV 1')),
                ('timehack_rdv2', models.CharField(blank=True, help_text='Enter time for flight rendevous point 2.', max_length=10, null=True, verbose_name='Time RDV 2')),
                ('fuel_fob', models.CharField(blank=True, help_text='Fuel FOB', max_length=10, null=True, verbose_name='Fuel FOB')),
                ('fuel_joker', models.CharField(blank=True, help_text='Fuel JOKER.', max_length=10, null=True, verbose_name='Fuel JOKER')),
                ('fuel_bingo', models.CharField(blank=True, help_text='Fuel BINGO.', max_length=10, null=True, verbose_name='Fuel BINGO')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('airframe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.airframe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailcode', models.CharField(blank=True, help_text='Enter A/C tail code.', max_length=20, null=True, verbose_name='Tail Code')),
                ('lasercode', models.CharField(blank=True, help_text='Enter A/C laser code.', max_length=10, null=True, verbose_name='Laser Code')),
                ('flight_lead', models.BooleanField(default=False, verbose_name='Flight Lead')),
                ('package_lead', models.BooleanField(default=False, verbose_name='Package Lead')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pilot', to=settings.AUTH_USER_MODEL)),
                ('rio_wso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rio', to=settings.AUTH_USER_MODEL, verbose_name='WSO/RIO')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.airframe')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.flight')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['-flight_lead', '-pilot'],
            },
        ),
        migrations.CreateModel(
            name='FlightImagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for flight.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/flight_images/', verbose_name='Flight Imagery')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, help_text='A number representing the mission order within the campaign.', verbose_name='mission number')),
                ('name', models.CharField(help_text='Enter Mission Name', max_length=200)),
                ('description', models.TextField(default='Mission description to be added here.', help_text='Enter Mission Description/Situation.')),
                ('brief', models.TextField(blank=True, help_text='Enter Detailed Mission Brief.', null=True, verbose_name='Tactical Mission Brief')),
                ('roe', models.TextField(blank=True, help_text='Enter Rules of Engagement', null=True, verbose_name='Rules of Engagement')),
                ('munitions_restrictions', models.TextField(blank=True, help_text='Enter any restrictions on use of munitions/weaponry.', null=True, verbose_name='munitions restrictions')),
                ('mission_time', models.TimeField(blank=True, default='10:00', help_text='Mission time in HH:MM format. (UTC)', max_length=5, null=True, verbose_name='mission Start Time (UTC)')),
                ('mission_date', models.DateTimeField(blank=True, help_text='Proposed mission Date. (UTC)', null=True, verbose_name='expected Mission Date (UTC)')),
                ('notify_discord', models.BooleanField(default=False, verbose_name='Send Notification To Discord if Webhook configured.')),
                ('mission_game_time', models.CharField(blank=True, help_text='Mission game start time in HH:MM format.', max_length=5, null=True, verbose_name='In-Game Mission Start Time')),
                ('mission_game_date', models.DateTimeField(blank=True, help_text='Mission game date.', null=True, verbose_name='In-Game Mission Date')),
                ('visibility', models.CharField(blank=True, help_text='Enter Visibility.', max_length=100, null=True, verbose_name='Visibility')),
                ('cloud_base', models.CharField(blank=True, help_text='Enter Cloud base in K of ft.', max_length=10, null=True, verbose_name='Cloud Base Altitude')),
                ('cloud_top', models.CharField(blank=True, help_text='Enter Cloud Tops in K of ft.', max_length=10, null=True, verbose_name='Cloud Tops')),
                ('wind_sl', models.CharField(blank=True, help_text='Enter Wind at Sea Level', max_length=20, null=True, verbose_name='Wind at Sea Level')),
                ('wind_7k', models.CharField(blank=True, help_text='Enter Wind at 7K ft.', max_length=20, null=True, verbose_name='Wind at 7K ft')),
                ('wind_26k', models.CharField(blank=True, help_text='Enter Wind at 26K ft.', max_length=20, null=True, verbose_name='Wind at 26K ft')),
                ('qnh', models.CharField(blank=True, help_text='Enter QNH', max_length=20, null=True, verbose_name='QNH')),
                ('qfe', models.CharField(blank=True, help_text='Enter QFE', max_length=20, null=True, verbose_name='QFE')),
                ('temp', models.CharField(blank=True, help_text='Enter temperature in C.', max_length=20, null=True, verbose_name='Temperature in Celcius')),
                ('sigwx', models.CharField(blank=True, help_text='SIGWX', max_length=20, null=True, verbose_name='SIGWX')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('discord_msg_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Discord Msg ID')),
                ('discord_api_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Discord API Event ID')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CombatFliteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter CombatFlite File Name', max_length=100, verbose_name='Combat Flight File Name')),
                ('combatflite_file', models.FileField(null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CombatFlite File Uploader')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
            ],
            options={
                'verbose_name': 'Combat Flite File',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='File Name')),
                ('mission_file', models.FileField(null=True, upload_to='')),
                ('file_type', models.CharField(choices=[('MIZ', 'Mission'), ('LIB', 'Liberation'), ('COM', 'CombatFlite'), ('TAC', 'Tacview'), ('OTH', 'Other')], default='MIZ', max_length=10)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='File Uploader')),
            ],
            options={
                'verbose_name': 'Mission File',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='MissionImagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for mission.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/mission_images/', verbose_name='Mission Imagery')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Package Name', max_length=200, verbose_name='Package Name')),
                ('frequency', models.CharField(blank=True, help_text='Enter Package Frequency', max_length=10, null=True, verbose_name='Package Frequency')),
                ('summary', models.TextField(blank=True, help_text='Use this field to describe the overall objectives for the package.', null=True, verbose_name='Summary of package objective')),
                ('package_coordination', models.TextField(blank=True, help_text='Use this field to enter in any notes that the package lead might need to use to coordinate other members of the package,', null=True, verbose_name='Notes for package co-ordination')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_created_by', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.package'),
        ),
        migrations.CreateModel(
            name='PackageImagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image for package.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/package_images/', verbose_name='Package Imagery')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.package')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Status Type', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Status',
                'verbose_name_plural': 'Campaign Status',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.status'),
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=50)),
                ('player_name', models.CharField(blank=True, max_length=30, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('tacan', models.CharField(blank=True, max_length=10, null=True)),
                ('altitude', models.CharField(blank=True, max_length=10, null=True)),
                ('speed', models.CharField(blank=True, max_length=10, null=True)),
                ('brc', models.CharField(blank=True, max_length=10, null=True)),
                ('icls', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Enter notes for support resource.', null=True)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
                ('support_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticsapp.supporttype')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter target name', max_length=50, verbose_name='Target Name')),
                ('lat', models.CharField(blank=True, help_text='Enter target latitude', max_length=200, null=True, verbose_name='Target Latitude')),
                ('long', models.CharField(blank=True, help_text='Enter target longitude.', max_length=200, null=True, verbose_name='Target Longitude')),
                ('elev', models.CharField(blank=True, help_text='Enter target elevation.', max_length=200, null=True, verbose_name='Target Elevation')),
                ('notes', models.TextField(blank=True, help_text='Any notes relevant to the target.', null=True, verbose_name='Notes on Target')),
                ('target_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload image of the target.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/target_images/', verbose_name='Target Image')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='targets',
            field=models.ManyToManyField(blank=True, to='opticsapp.target'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.task'),
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Terrain Map Name.', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terrain',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='dcs_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.terrain', verbose_name='DCS Map'),
        ),
        migrations.CreateModel(
            name='ThreatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(default='Threat description to be added here.', help_text='Enter Threat Description/Situation.')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.mission')),
                ('threat_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.threatreference')),
                ('threat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticsapp.threattype')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('profile_image', django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format=None, help_text='User profile image file.', keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='user/profile_images/', verbose_name='User profile image.')),
                ('timezone', models.CharField(default='Australia/Melbourne', max_length=100)),
                ('squadron', models.ForeignKey(default=optics.opticsapp.models.Squadron.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='opticsapp.squadron', verbose_name='Squadron')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='WaypointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waypoint Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1, help_text='A number representing the waypoint order.', verbose_name='waypoint number')),
                ('lat', models.CharField(blank=True, max_length=15, null=True)),
                ('long', models.CharField(blank=True, max_length=15, null=True)),
                ('elevation', models.CharField(blank=True, max_length=15, null=True)),
                ('tot', models.CharField(blank=True, max_length=15, null=True, verbose_name='time on Target')),
                ('notes', models.TextField(blank=True, help_text='Enter notes for the waypoint.', null=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opticsapp.flight')),
                ('waypoint_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticsapp.waypointtype')),
            ],
        ),
    ]
