# Generated by Django 5.0.3 on 2024-03-06 10:59

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aoImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='An image of the Area of Operations.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/ao_images', verbose_name='area of Operations Image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Campaign Image File.', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='campaign/thumbnails/', verbose_name='Campaign Image Thumbnail.'),
        ),
        migrations.AlterField(
            model_name='flightimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for flight.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/flight_images/', verbose_name='Flight Imagery'),
        ),
        migrations.AlterField(
            model_name='missionimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for mission.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/mission_images/', verbose_name='Mission Imagery'),
        ),
        migrations.AlterField(
            model_name='packageimagery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for package.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/package_images/', verbose_name='Package Imagery'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image of the target.', keep_meta=True, null=True, quality=-1, scale=None, size=[1500, 1200], upload_to='campaign/mission/target_images/', verbose_name='Target Image'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='threatreference',
            name='rwr_image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Upload image for rwr.', keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='threats', verbose_name='RWR Identifier'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='assets/img/avatars/pilot1.png', force_format='PNG', help_text='User profile image file.', keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='user/profile_images/', verbose_name='User profile image.'),
        ),
    ]
