# Generated by Django 5.0.3 on 2024-03-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionimagery',
            options={'ordering': ['-mission'], 'verbose_name_plural': 'Mission Imagery'},
        ),
        migrations.DeleteModel(
            name='CombatFliteFile',
        ),
    ]
