# Generated by Django 5.0.3 on 2024-03-26 10:16

import csv

from django.db import migrations, models

import optics.opticsapp.models.Airframe


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0002_alter_missionimagery_options_delete_combatflitefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypointtype",
            name="dcs_mapping",
            field=models.CharField(
                choices=[
                    ("Not Mapped", "Not Mapped"),
                    ("TakeOffParking", "Takeoffparking"),
                    ("TakeOffParkingHot", "Takeoffparkinghot"),
                    ("Turning Point", "Turning Point"),
                ],
                default="Not Mapped",
                max_length=50,
            ),
        ),
    ]
