# Generated by Django 5.0.3 on 2024-04-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0002_alter_missionimagery_options_delete_combatflitefile"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="waypointtype",
        #     name="dcs_mapping",
        #     field=models.CharField(
        #         choices=[
        #             ("Not Mapped", "Not Mapped"),
        #             ("TakeOffParking", "Takeoffparking"),
        #             ("TakeOffParkingHot", "Takeoffparkinghot"),
        #             ("Turning Point", "Turning Point"),
        #         ],
        #         default="Not Mapped",
        #         max_length=50,
        #     ),
        # ),
        migrations.CreateModel(
            name="DCSAirframe",
            fields=[
                (
                    "dcsname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="airframe",
            name="dcsname",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opticsapp.dcsairframe",
            ),
        ),
    ]
