# Generated by Django 5.0.3 on 2024-03-27 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("opticsapp", "0003_airframe_dcs_mapping_waypointtype_dcs_mapping"),
        ("opticsapp", "0004_remove_airframe_dcs_mapping_dcsairframe"),
        ("opticsapp", "0005_alter_dcsairframe_airframe"),
        ("opticsapp", "0006_remove_dcsairframe_airframe_airframe_dcsname"),
        ("opticsapp", "0007_alter_dcsairframe_dcsname"),
        ("opticsapp", "0008_alter_airframe_dcsname"),
        ("opticsapp", "0009_alter_dcsairframe_dcsname"),
    ]

    dependencies = [
        ("opticsapp", "0002_alter_missionimagery_options_delete_combatflitefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypointtype",
            name="dcs_mapping",
            field=models.CharField(
                choices=[
                    ("Not Mapped", "Not Mapped"),
                    ("TakeOffParking", "Takeoffparking"),
                    ("TakeOffParkingHot", "Takeoffparkinghot"),
                    ("Turning Point", "Turning Point"),
                ],
                default="Not Mapped",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DCSAirframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dcsname", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="airframe",
            name="dcsname",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opticsapp.dcsairframe",
            ),
        ),
    ]
