# Generated by Django 5.1.1 on 2024-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticsapp', '0002_alter_missionimagery_options_delete_combatflitefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='If in draft the mission does not appear to non-admins.'),
        ),
    ]
