# Generated by Django 5.0.3 on 2024-03-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0003_airframe_dcs_mapping_waypointtype_dcs_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="DCSAirframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dcsname", models.CharField(max_length=50)),
                (
                    "airframe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="opticsapp.airframe",
                    ),
                ),
            ],
        ),
    ]
