# Generated by Django 5.0.3 on 2024-03-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0004_remove_airframe_dcs_mapping_dcsairframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcsairframe",
            name="airframe",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opticsapp.airframe",
            ),
        ),
    ]
