# Generated by Django 5.0.3 on 2024-03-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0005_alter_dcsairframe_airframe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dcsairframe",
            name="airframe",
        ),
        migrations.AddField(
            model_name="airframe",
            name="dcsname",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="opticsapp.dcsairframe",
            ),
        ),
    ]
