# Generated by Django 5.0.3 on 2024-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0006_remove_dcsairframe_airframe_airframe_dcsname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcsairframe",
            name="dcsname",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
