# Generated by Django 5.0.3 on 2024-03-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opticsapp", "0008_alter_airframe_dcsname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcsairframe",
            name="dcsname",
            field=models.CharField(max_length=50),
        ),
    ]
