# Generated by Django 5.0.3 on 2024-03-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "opticsapp",
            "0003_airframe_dcs_mapping_waypointtype_dcs_mapping_squashed_0009_alter_dcsairframe_dcsname",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dcsairframe",
            name="id",
        ),
        migrations.AlterField(
            model_name="dcsairframe",
            name="dcsname",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
